server:
  port: 8805
spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JavaCodeMing/Spring-Cloud-Config.git
          username: xxxxxx
          password: xxxxxx
          #开启启动时直接从git获取配置
          clone-on-start: true
  security: #配置用户名和密码
    user:
      name: admin
      password: 123456
