server:
  port: 8103
spring:
  application:
    name: eureka-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #加密后注册中心地址格式: http://${username}:${password}@${hostname}:${port}/eureka/
      defaultZone: http://conan:123456@localhost:8004/eureka/
