server:
  port: 8102
spring:
  application:
    name: eureka-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #同时注册到两个注册中心
      defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/
