server:
  port: 9005
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        #配置admin-server地址
        url: http://localhost:9001
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  #添加开启admin的日志监控
  file:
    name: admin-client.log
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
