server:
  port: 8804
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JavaCodeMing/Spring-Cloud-Config.git
          username: xxxxxx
          password: xxxxxx
          clone-on-start: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  #暴露bus刷新配置的端点
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
