spring:
  application:
    name: Zuul-Gateway
server:
  port: 12580
eureka:
  client:
    service-url:
      defaultZone: http://kimi:123456@peer1:8080/eureka/,http://kimi:123456@peer2:8081/eureka/
zuul:
  routes:
    # 所有符合path上规则的访问都将被路由转发到url地址上
    api-a:
      path: /api-a/**
      url: http://localhost:8082
    api-b:
      path: /api-b/**
      serviceId: Eureka-Client
    api-c:
      path: /api-c/**
      serviceId: Server-Consumer
    api-e:
      path: /api-e/**
      url: forward:/test