server:
  port: 8801
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: prefixpath_route
          #此处需要使用lb协议
          uri: lb://user-service
          predicates:
            - Method=GET
          filters:
            - PrefixPath=/user
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
