server:
  port: 8505
spring:
  application:
    name: turbine-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
turbine:
  #指定需要收集信息的服务名称
  app-config: hystrix-service
  #指定服务所属集群
  cluster-name-expression: new String('default')
  #以主机名和端口号来区分服务
  combine-host-port: true
